name: Run test VS

on:
  push:
    branches:
    - develop
    - feature/*

jobs:
  test_vs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        define:
        - ''

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: 'sudo apt update

        sudo apt install -y g++

        '
    - name: Build and Run C++ application
      run: 'g++ -std=c++11 -Wall -Werror ${{ matrix.define }} -O2 -I ./python_optimization -I ./optimization_utility
        -I ./external_libraries/python_control_to_cpp/python_control -I ./external_libraries/python_numpy_to_cpp/python_numpy
        -I ./external_libraries/python_numpy_to_cpp/base_matrix -I ./external_libraries/python_math_to_cpp/base_math
        -I ./external_libraries/python_math_to_cpp/python_math -I ./external_libraries/base_utility_cpp/base_utility
        -I ./test_vs/MCAP_tester/include -o ./test_vs/app ./test_vs/test_vs_main.cpp

        ./test_vs/app

        '
