name: Run samples

on:
  push:
    branches:
    - develop
    - feature/*

jobs:
  run_samples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        define:
        - ''

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: 'sudo apt update

        sudo apt install -y build-essential

        sudo apt install -y python3.12

        sudo apt install -y python3.12-dev

        sudo apt install -y python3.12-venv

        '
    - name: Set up Python environment
      run: 'python3.12 -m venv /opt/venv_py_sim_manager

        /opt/venv_py_sim_manager/bin/pip install --upgrade pip

        /opt/venv_py_sim_manager/bin/pip install --upgrade setuptools

        /opt/venv_py_sim_manager/bin/pip install numpy sympy scipy astor

        '
    - name: Run samples
      env:
        MPLBACKEND: Agg
      run: '/opt/venv_py_sim_manager/bin/python3 ./sample/sqp_pendulum_demo.py

        g++ -std=c++11 -Wall -Werror -O2 -I ./python_optimization
          -I ./optimization_utility -I ./external_libraries/python_control_to_cpp/python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/sqp_pendulum_demo.cpp

        ./sample/app

        /opt/venv_py_sim_manager/bin/python3 ./sample/sqp_pendulum_demo_op_en.py

        g++ -std=c++11 -Wall -Werror -O2 -I ./python_optimization
          -I ./optimization_utility -I ./external_libraries/python_control_to_cpp/python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/sqp_pendulum_demo_op_en.cpp

        ./sample/app

        /opt/venv_py_sim_manager/bin/python3 ./sample/sqp_2_mass_spring_damper_demo.py

        g++ -std=c++11 -Wall -Werror -O2 -I ./python_optimization
          -I ./optimization_utility -I ./external_libraries/python_control_to_cpp/python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/sqp_2_mass_spring_damper_demo.cpp

        ./sample/app

        g++ -std=c++11 -Wall -Werror -O2 -I ./python_optimization
          -I ./optimization_utility -I ./external_libraries/python_control_to_cpp/python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/qp_active_set_demo_1.cpp

        ./sample/app

        g++ -std=c++11 -Wall -Werror -O2 -I ./python_optimization
          -I ./optimization_utility -I ./external_libraries/python_control_to_cpp/python_control
          -I ./external_libraries/python_numpy_to_cpp/python_numpy -I ./external_libraries/python_numpy_to_cpp/base_matrix
          -I ./external_libraries/python_math_to_cpp/base_math -I ./external_libraries/python_math_to_cpp/python_math
          -I ./external_libraries/base_utility_cpp/base_utility
          -o ./sample/app ./sample/qp_active_set_demo_2.cpp

        ./sample/app

        '
